services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - photo-organizer
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  photo-organizer:
    driver: bridge
